# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-20 01:45
from __future__ import unicode_literals

from django.db import migrations


def empty(*args):
    pass


def create_category_types(apps, *args):
    types = ["Income", "Expense"]

    CategoryType = apps.get_model("transactions", "CategoryType")

    for _type in types:
        CategoryType.objects.get_or_create(name=_type)


def foward_migration(apps, *args):
    incomes = [
        "My take-home pay",
        "My spouse/partner's take-home pay",
        "Business income (profit)",
        "Interest / earning on investments",
        "Rental property income",
        "Retirement income (pension, RIF, annuity, etc...)",
        "Child support income",
        "Social assistance",
        "Student loan (money received)",
        "Canada child benefit",
        "Allowance",
        "Other Income"
    ]

    categories = [
        "Regular savings (Major purchases, etc...)",
        "Emergency funds",
        "Tax-Free Savings Account",
        "Retirement Savings (e.g. RRSP contributions)",
        "Registered Education Savings Plan (RESP)",
        "Non registered investments (GICs, mutual funds, etc...)",
        "Other Savings",

        "Rent",
        "Mortgage payments",
        "Property taxes",
        "Home / tenant insurance",
        "Condo fees",

        "Repairs and maintenance",
        "Painting and decorating",
        "Plumbing",
        "Electrical",
        "Home improvements",
        "Appliances",
        "Gardening / landscaping",
        "Household services",
        "Other repairs and maintainance",


        "Furniture",
        "Appliances",
        "House contents",
        "Other household items",

        "Utilities",
        "Electricity",
        "Gas",
        "Water",
        "Telephone",
        "Cable or satellite",
        "Internet",
        "Combined (if you pay telephone, Internet, TV, etc. together)",

        "Life and health insurance",
        "Medical",
        "Your life",
        "Your partner's life",
        "Your disability",
        "Your partner's disability",
        "Other Insurance",

        "Food and groceries",
        "Groceries",
        "Work lunches (bought)",
        "Take-out / order in",
        "Other food (for example, daily coffee purchases)",

        "Vehicle licensing and registration",
        "Vehicle insurance",
        "Gas",
        "Maintenance",
        "Vehicle loan/lease payments",
        "Parking",
        "Transit pass (bus and / or train)",
        "Taxi fares",
        "Other transportation",

        "Daycare",
        "After school / holiday care",
        "Babysitting",
        "Child support payments",
        "Children's allowance",
        "Other child care",

        "School expenses (tuition, fees, etc...)",
        "Textbooks and stationery",
        "School trips",
        "Professional or association dues",
        "Other education or profession development",

        "Student loan",
        "Credit cards",
        "Line of credit",
        "Other debt",

        "Restaurants / Dining out",
        "Nightlife (bars, cafes, etc…)",
        "Club memberships (e.g. gym)",
        "Children's activities",
        "Tickets for sporting events, plays and concerts",
        "Outdoor recreation (e.g. camping, skiing)",
        "Sports gear (e.g. hockey equipment)",
        "Hobbies ( e.g. stamp collection, musical instruments)",
        "Movies",
        "Newspapers / magazines / books",
        "Alcohol",
        "Tobacco (e.g. cigarettes)",
        "Other forms of entertainment",

        "Vacation",
        "Travel insurance",
        "Other",

        "Clothing",
        "Adults' clothes / shoes",
        "Children's clothes / shoes",
        "Laundry / dry cleaning",
        "Accessories",

        "Personal care / grooming",
        "Cosmetics / toiletries",
        "Hairdresser / barbers",
        "Other personal",

        "Doctor",
        "Prescriptions and medicines",
        "Dentist",
        "Other medical",


        "Banking fees",
        "Mobile phone(s)",
        "Professional (legal, financial advice, etc...)",
        "Other services",

        "Gifts",
        "Gifts (holiday, birthdays, special events, etc...)",

        "Charitable donations",

        "Vet expenses",
        "Pet food",
        "Other",
    ]

    Category = apps.get_model('transactions', 'Category')

    for index, cat in enumerate(incomes):
        Category.objects.get_or_create(name=cat, type_id=1, defaults={
            'order': index
        })

    for index, cat in enumerate(categories, index):
        Category.objects.get_or_create(name=cat, type_id=2, defaults={
            'order': index
        })


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_category_types, empty),
        migrations.RunPython(foward_migration, empty)
    ]
