# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-19 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_descriptioninfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptioninfo',
            name='description',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transactions.Description'),
            preserve_default=False,
        ),
    ]
