# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-20 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_descriptioninfo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptioninfo',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_info', to='transactions.Description'),
        ),
    ]
