# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-05 16:03
from __future__ import unicode_literals

from django.db import migrations, models


def order(categories):
    for index, category in enumerate(categories, start=1):
        category.order = index
        category.save()

        children = category.children.all()
        order(children)


def order_categories(apps, *args):
    Category = apps.get_model('transactions.Category')

    root_categories = Category.objects.filter(parent_category_id=None)

    order(root_categories)


def empty(apps, *args):
    # Empty because the column gets deleted when reversing this migration
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_category_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),

        migrations.RunPython(order_categories, empty)
    ]
