# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-08 04:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def empty(*args):
    pass

def move_descriptions(apps, *args):
    Transaction = apps.get_model('transactions', 'Transaction')
    Description = apps.get_model('transactions', 'Description')

    for transaction in Transaction.objects.all():
        transaction.name = Description.objects.get(
            name=transaction.description)
        transaction.save()


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='transactions.Description'),
            preserve_default=False,
        ),
        migrations.RunPython(move_descriptions, empty),
    ]
