# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-08 05:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_transaction_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
    ]
